language: python


python:
  - 3.6

services:
  - postgresql
addons:
  postgresql: "9.6"
install:
  - pip install pipenv 
  - pipenv sync


jobs:  
  include:
    - stage: "Tests" # naming the Tests stage
      script: python manage.py test
      name: "Unit Tests"
    - script: flake8
      name: "Linting"   




