language: python

cache: pip

python:
  - 3.6

services:
  - docker


install:
  - pip install pipenv docker-compose
  - pipenv sync
  - docker-compose up -d

jobs:  
  include:
    - stage: "Tests" # naming the Tests stage
      script: python manage.py test
      name: "Unit Tests"
    - script: flake8
      name: "Linting"   




