language: python


python:
  - 3.6

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432

install:
  - pip install pipenv 
  - pipenv sync
  - psql -c "CREATE DATABASE postgres;" -U postgres

jobs:  
  include:
    - stage: "Tests" # naming the Tests stage
      script: python manage.py test
      name: "Unit Tests"
    - script: flake8
      name: "Linting"   




