language: python

cache: pip

python:
  - 3.6

services:
  - postgresql


install:
  - pip install pipenv
  - pipenv sync

jobs:  
  include:
    - stage: "Unit Tests"                # naming the Tests stage
      script: python manage.py test
    - stage: 'Linting'
      script: flake8   




